import avocadoGreenBowlImage from "../assets/images/Avocado Green Bowl.jpg";
import bananaOatMuffinImage from "../assets/images/Banana Oat Muffin.jpg";
import brownSugarMilkTeaImage from "../assets/images/Brown Sugar Milk Tea.jpg";
import cheeseSticksImage from "../assets/images/Cheese Sticks.jpg";
import chickenBitesImage from "../assets/images/Chicken Bites.jpg";
import chocomaltImage from "../assets/images/Chocomalt Cream Puff Red Milk Tea.png";
import freshFruitCupImage from "../assets/images/Fresh Fruit Cup.jpg";
import freshSaladImage from "../assets/images/fresh_salad.jpg";
import granolaEnergyBitesImage from "../assets/images/Granola Energy Bites.jpg";
import matchaMilkTeaImage from "../assets/images/Matcha Milk Tea.jpg";
import sweetPotatoFriesImage from "../assets/images/Sweet Potato Fries.jpg";
import veggieSpringRollsImage from "../assets/images/Veggie Spring Rolls.jpg";
import wintermelonMilkTeaImage from "../assets/images/Wintermelon Milk Tea.jpg";
import yogurtParfaitImage from "../assets/images/Yogurt Parfait.jpg";
import { FeedPost, FeedPostKind } from "../types";
import { repairMojibakeText } from "../utils/text";

const ADMIN_USER_ID = "admin-bell-fresh";

interface FeedTemplate {
  emoji: string;
  content: string;
  kind: FeedPostKind;
  imageUrl?: string;
  source?: string;
  isAnnouncement?: boolean;
}

const rawFeedSeedPosts: FeedPost[] = [
  {
    id: "feed-welcome",
    authorId: ADMIN_USER_ID,
    content: "Welcome to Bell Fresh Community. Share your cravings, combos, and latest order moments here.",
    emoji: "🥗",
    kind: "update",
    source: "Bell Fresh",
    createdAt: "2026-03-24T08:00:00.000Z",
    likedBy: [],
    isAnnouncement: true,
    imageUrl: freshSaladImage,
    comments: [],
  },
  {
    id: "feed-breaking-snacks",
    authorId: ADMIN_USER_ID,
    content: "Breaking menu update: Light Snacks are getting more attention tonight, especially Sweet Potato Fries and Chicken Bites.",
    emoji: "🆕",
    kind: "news",
    source: "Bell Fresh Kitchen",
    createdAt: "2026-03-24T08:22:00.000Z",
    likedBy: [],
    autoGenerated: true,
    imageUrl: sweetPotatoFriesImage,
    comments: [],
  },
  {
    id: "feed-meme-milk-tea",
    authorId: ADMIN_USER_ID,
    content: "Me: I’ll order just one thing. Also me 2 minutes later: salad, milk tea, fries, and dessert please.",
    emoji: "😂",
    kind: "meme",
    source: "Bell Fresh Memes",
    createdAt: "2026-03-24T08:40:00.000Z",
    likedBy: [],
    autoGenerated: true,
    imageUrl: chocomaltImage,
    comments: [],
  },
  {
    id: "feed-photo-parfait",
    authorId: ADMIN_USER_ID,
    content: "Fresh photo drop: Yogurt Parfait is one of the easiest light picks when you want something cold and sweet.",
    emoji: "📸",
    kind: "photo",
    source: "Bell Fresh Camera Roll",
    createdAt: "2026-03-24T09:00:00.000Z",
    likedBy: [],
    autoGenerated: true,
    imageUrl: yogurtParfaitImage,
    comments: [],
  },
  {
    id: "feed-news-checkout",
    authorId: ADMIN_USER_ID,
    content: "Save your address in Profile and your next checkout gets much faster. You can still edit it anytime.",
    emoji: "📍",
    kind: "news",
    source: "Bell Fresh Tips",
    createdAt: "2026-03-24T09:18:00.000Z",
    likedBy: [],
    autoGenerated: true,
    imageUrl: avocadoGreenBowlImage,
    comments: [],
  },
  {
    id: "feed-meme-snack",
    authorId: ADMIN_USER_ID,
    content: "Current mood: saying I want something light, then adding Cheese Sticks because balance matters.",
    emoji: "🤣",
    kind: "meme",
    source: "Snack Energy",
    createdAt: "2026-03-24T09:42:00.000Z",
    likedBy: [],
    autoGenerated: true,
    imageUrl: cheeseSticksImage,
    comments: [],
  },
  {
    id: "feed-relatable-rain",
    authorId: ADMIN_USER_ID,
    content: "Rainy day mood: a warm snack, a cold milk tea, and pretending this is definitely the last order today.",
    emoji: "🌧️",
    kind: "update",
    source: "Bell Fresh Community",
    createdAt: "2026-03-24T09:56:00.000Z",
    likedBy: [],
    autoGenerated: true,
    imageUrl: wintermelonMilkTeaImage,
    comments: [],
  },
];

const rawAutoFeedTemplates: FeedTemplate[] = [
  {
    emoji: "🔥",
    content: "Live kitchen pulse: Chicken Bites are one of the hottest picks right now.",
    kind: "news",
    source: "Live Kitchen",
    imageUrl: chickenBitesImage,
  },
  {
    emoji: "📸",
    content: "Photo update: Brown Sugar Milk Tea just landed another round of orders.",
    kind: "photo",
    source: "Bell Fresh Camera Roll",
    imageUrl: brownSugarMilkTeaImage,
  },
  {
    emoji: "😂",
    content: "Meme of the minute: when you open Bell Fresh for salad and somehow leave with fries and dessert too.",
    kind: "meme",
    source: "Bell Fresh Memes",
    imageUrl: freshFruitCupImage,
  },
  {
    emoji: "📰",
    content: "Fresh update: lighter snack combos are trending with fruit cups and parfaits this hour.",
    kind: "news",
    source: "Bell Fresh Trends",
    imageUrl: freshFruitCupImage,
  },
  {
    emoji: "💚",
    content: "Quick update: fresh bowl photos keep getting love from customers who want lighter lunch options.",
    kind: "update",
    source: "Bell Fresh Community",
    imageUrl: freshSaladImage,
  },
  {
    emoji: "☁️",
    content: "Relatable news: cloudy weather keeps pushing more people toward milk tea and comfort snacks.",
    kind: "news",
    source: "Bell Fresh Mood Meter",
    imageUrl: matchaMilkTeaImage,
  },
  {
    emoji: "😅",
    content: "Very relatable: people keep saying they only want one snack, then add a drink, then add dessert.",
    kind: "meme",
    source: "Bell Fresh Memes",
    imageUrl: bananaOatMuffinImage,
  },
  {
    emoji: "📷",
    content: "Fresh photo card: Veggie Spring Rolls are making the menu look extra crispy today.",
    kind: "photo",
    source: "Bell Fresh Camera Roll",
    imageUrl: veggieSpringRollsImage,
  },
  {
    emoji: "🧋",
    content: "Now trending: Matcha and Wintermelon keep showing up in quick afternoon orders.",
    kind: "news",
    source: "Bell Fresh Trends",
    imageUrl: wintermelonMilkTeaImage,
  },
  {
    emoji: "🥹",
    content: "Small win news: people love saved addresses because checkout feels way less stressful on the second order.",
    kind: "update",
    source: "Bell Fresh Tips",
    imageUrl: avocadoGreenBowlImage,
  },
  {
    emoji: "🤣",
    content: "Meme drop: ordering a light snack and then acting surprised when fries somehow join the cart.",
    kind: "meme",
    source: "Snack Energy",
    imageUrl: sweetPotatoFriesImage,
  },
  {
    emoji: "📸",
    content: "Photo update: Granola Energy Bites are getting attention from the snack-first crowd.",
    kind: "photo",
    source: "Bell Fresh Camera Roll",
    imageUrl: granolaEnergyBitesImage,
  },
  {
    emoji: "🌙",
    content: "Late-night relatable news: more people are building quick snack-and-tea combos after dinner.",
    kind: "news",
    source: "Bell Fresh Night Feed",
    imageUrl: chocomaltImage,
  },
  {
    emoji: "🍓",
    content: "Fresh picks update: Yogurt Parfait and Fresh Fruit Cup are the cooler side of the menu right now.",
    kind: "update",
    source: "Bell Fresh Community",
    imageUrl: yogurtParfaitImage,
  },
  {
    emoji: "🚌",
    content: "Commute mode news: grab-and-go items keep getting attention from people who want something fast.",
    kind: "news",
    source: "Bell Fresh Rush Hour",
    imageUrl: chickenBitesImage,
  },
];

export const feedSeedPosts: FeedPost[] = rawFeedSeedPosts.map((post) => ({
  ...post,
  content: repairMojibakeText(post.content),
  emoji: post.emoji ? repairMojibakeText(post.emoji) : undefined,
  source: post.source ? repairMojibakeText(post.source) : undefined,
}));

export const autoFeedTemplates: FeedTemplate[] = rawAutoFeedTemplates.map((template) => ({
  ...template,
  content: repairMojibakeText(template.content),
  emoji: repairMojibakeText(template.emoji),
  source: template.source ? repairMojibakeText(template.source) : undefined,
}));
